[book]
authors = ["Nordine Bittich"]
language = "en"
multilingual = false
src = "src"
title = "Openartcoded - Documentation"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "navy"

[output.html.search]
limit-results = 15